version: '3.5' # 3.5 because we use centos7

services:
  bep-api:
    #build: .
    image: bepolytech/bepi:latest
    container_name: bep-api
    restart: unless-stopped
    env_file:
      - ./app/.env
    #environment:
    #  - API_KEY=
    #  - UTC_OFFSET= # in seconds, ex: 3600 = UTC+1
    #  - MAX_TIME= # max time before the status is considered unknown, in ms, ex: 300000 = 5 minutes
    ###volumes:
    ###  - ./data:/data
    ports:
      - 8000:8000
    network_mode: host
