version: '3.9'

services:
  bep-api:
    #build: .
    image: bepolytech/bepi:latest
    container_name: bep-api
    restart: unless-stopped
    env_file:
      - ./app/.env
    #volumes:
    #  - ./data:/data
    ports:
      - 8000:80
